### ISSUE TITLE
Object counting with YOLOv8

### ISSUE THREAD

**Issue by pderrenger** [ultralytics/mkdocs#51]
How can I count objects in a video stream with YOLOv8?

**Comment by glenn-jocher** [comment]
Hey there! 🚀 To count objects in a video stream using YOLOv8, you can use the `ObjectCounter` from the `solutions` module. Here's a basic example to get you started:

```python
import cv2
from ultralytics import YOLO, solutions

# Load the model
model = YOLO("yolov8n.pt")

# Open video stream
cap = cv2.VideoCapture("path/to/video.mp4")
assert cap.isOpened(), "Error reading video file"

# Define region points for counting (optional)
region_points = [(20, 400), (1080, 400)]

# Initialize Object Counter
counter = solutions.ObjectCounter(
    view_img=True,
    reg_pts=region_points,
    classes_names=model.names,
    draw_tracks=True,
    line_thickness=2,
)

# Process video frames
while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        break
    tracks = model.track(im0, persist=True, show=False)
    im0 = counter.start_counting(im0, tracks)
    cv2.imshow('Object Counting', im0)
    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
```

This script will display the video stream with counted objects. Adjust `region_points` to specify where in the frame you want to count objects. For more details, check out the Ultralytics documentation at https://docs.ultralytics.com. Happy coding! 😊

**Comment by glenn-jocher** [comment]
@pderrenger hello! To count objects in a video stream using YOLOv8, you can utilize the `ObjectCounter` from the Ultralytics solutions. Here's a basic example to get you started:

```python
import cv2
from ultralytics import YOLO, solutions

# Load the YOLO model
model = YOLO("yolov8n.pt")

# Open video stream
cap = cv2.VideoCapture("path/to/video.mp4")
assert cap.isOpened(), "Error reading video file"

# Define region points for counting (optional)
region_points = [(20, 400), (1080, 400)]

# Initialize Object Counter
counter = solutions.ObjectCounter(
    view_img=True,
    reg_pts=region_points,
    classes_names=model.names,
    draw_tracks=True,
    line_thickness=2,
)

# Process video frames
while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        break
    tracks = model.track(im0, persist=True, show=False)
    im0 = counter.start_counting(im0, tracks)
    cv2.imshow('Object Counting', im0)
    if cv2.waitKey(1) == ord('q'):
        break

# Cleanup
cap.release()
cv2.destroyAllWindows()
```

This script will count objects as they appear in the defined region. Adjust the `region_points` to fit the area you're interested in. For more detailed guidance and customization options, check out the Ultralytics documentation at https://docs.ultralytics.com. Happy counting! 😊

**Comment by glenn-jocher** [comment]
Hello! To count objects in a video stream using YOLOv8, you can use the `ObjectCounter` from the Ultralytics solutions. Here's a basic example to get you started:

```python
import cv2
from ultralytics import YOLO, solutions

# Load the model
model = YOLO("yolov8n.pt")

# Open video stream
cap = cv2.VideoCapture("path/to/video.mp4")
assert cap.isOpened(), "Error reading video file"

# Initialize Object Counter
counter = solutions.ObjectCounter(view_img=True, classes_names=model.names)

# Process video frames
while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        break
    tracks = model.track(im0, persist=True, show=False)
    im0 = counter.start_counting(im0, tracks)
    cv2.imshow('Object Counting', im0)
    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
```

This script will display the video stream with counted objects. Adjust the path to your video and model as needed. For more detailed setups and options, you might want to check the Ultralytics documentation. Happy coding! 😊

**Comment by glenn-jocher** [comment]
Hello! To count objects in a video stream using YOLOv8, you can run the model on each frame of the video and tally the detections based on their class. Here's a basic example using Python:

```python
import cv2
from yolov8 import YOLOv8

# Initialize the model
model = YOLOv8(weights='yolov8.pt')

# Open the video
cap = cv2.VideoCapture('path_to_video.mp4')
object_counts = {}

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Make detections
    results = model(frame)

    # Count objects
    for det in results.xyxy[0]:
        class_id = int(det[-1])
        if class_id in object_counts:
            object_counts[class_id] += 1
        else:
            object_counts[class_id] = 1

cap.release()

# Print results
for class_id, count in object_counts.items():
    print(f'Class {class_id}: {count}')
```

This script will count the occurrences of each class detected in the video. Adjust the `weights` parameter to the specific model weights you are using. Happy coding! 😊

**Comment by glenn-jocher** [comment]
Hello! To count objects in a video stream using YOLOv8, you can use the following command after setting up your environment:

```bash
python yolov8_region_counter.py --source "path/to/video.mp4" --save-img
```

This command will run the model on your video file and save the images with counted objects. Make sure to replace `"path/to/video.mp4"` with the path to your video file. For real-time counting, you can use your webcam by setting `--source 0`.

For more details on setting up and running the model, you can refer to the documentation at https://docs.ultralytics.com. Happy counting! 😊

**Comment by glenn-jocher** [comment]
Hello! Counting objects in a video stream with YOLOv8 is quite straightforward. Here’s a basic example to get you started:

```python
import cv2
from ultralytics import YOLO, solutions

# Load the YOLO model
model = YOLO("yolov8n.pt")

# Open video stream
cap = cv2.VideoCapture("path/to/video/file.mp4")
assert cap.isOpened(), "Error reading video file"

# Initialize Object Counter with default settings
counter = solutions.ObjectCounter()

while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        break
    # Perform object tracking
    tracks = model.track(im0, persist=True, show=False)
    # Start object counting
    im0 = counter.start_counting(im0, tracks)
    cv2.imshow('Object Counting', im0)
    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
```

This script will count and display the objects as they appear in the video. You can customize the `ObjectCounter` for specific classes or regions by adjusting its parameters. For more detailed setups and options, you might want to check the documentation at https://docs.ultralytics.com/guides/object-counting/. Happy coding! 😊
